[package]
name = "interesting-hacker"
version = "0.1.0"
authors = ["lewisjnerd@gmail.com"]

[dependencies]
clap = "2.31.2"
reqwest = "0.8.2"
serde_json = "1.0"
serde = "1.0"
regex = "0.2"
toml = "0.4.6"
rayon = "1.0"